
services:

  web:
    build: .
    command: bash -c "alembic upgrade head && python main.py"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    ports:
      - 8000:8000
    env_file: .env
    networks:
      - parser_network

  db:
    image: bitnami/postgresql
    # restart: always
    container_name: parser_database 
    env_file: .env
    user: root
    volumes:
      - db_docker:/bitnami/postgresql
    ports:
      - ${DATABASE_PORT}:5432
    expose:
      - ${DATABASE_PORT}
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    networks:
      - parser_network

  redis:
    image: redis:alpine
    container_name: parser_redis
    # restart: always
    ports:
      - ${REDIS_PORT}:6379
    expose:
      - ${REDIS_PORT} 
    env_file: .env
    networks:
      - parser_network 

volumes:
  db_docker:

networks:
  parser_network:
    driver: bridge
