
services:

  web:
    build: .
    command: uvicorn main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    depends_on:
      - db
      - redis ports:
      - 8008:8080
    env_file: .env
    networks:
      - backend

  db:
    image: bitnami/postgresql
    restart: always
    container_name: cortex_database
    env_file: ".env"
    user: root
    volumes:
      - db_docker:/bitnami/postgresql
      - ./create-dbs.sql:/docker-entrypoint-initdb.d/create-dbs.sql
    ports:
      - 5432:5432
    expose:
      - 5432
    environment:
      - POSTGRESQL_USERNAME=${DATABASE_USER}
      - POSTGRESQL_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRESQL_DATABASE=${DATABASE_NAME}
    networks:
      - cp_network
  redis:
    image: redis:alpine
    container_name: cortex_redis
    restart: always
    ports:
      - 6379:6379
    expose:
      - 6379
    env_file: .env
    networks:
      - cp_network 
volumes:
  db_docker:
