"""empty message

Revision ID: a9bd181b2a98
Revises: a5e70066868c
Create Date: 2025-02-26 09:07:04.553401

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bd181b2a98'
down_revision: Union[str, None] = 'a5e70066868c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('experiences', 'description',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.VARCHAR(length=1000),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'technologies_used',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'technologies_used',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=1000),
               existing_nullable=True)
    op.alter_column('experiences', 'description',
               existing_type=sa.TEXT(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=True)
    # ### end Alembic commands ###
